server:
  port: 9085

spring:
  application:
    name: skillsync-session-service
  config:
    import: "optional:configserver:http://config-server:9888"
  datasource:
    url: jdbc:mysql://mysql:3306/skillsync_session_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Welcome@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      enabled: true

# Enable ServiceJwtFilter from skillsync-common
skillsync:
  service-jwt-filter:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:9761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    in.skillsync: DEBUG
    org.springframework.amqp: INFO
